### ISSUE TITLE
undefined throws error as I have strict checks on 

### ISSUE THREAD

**Issue by iangregsondev** [bahmutov/mocked-env#144]
Thanks great library!

But the undefined is throwing a type error, i suppose a picture is worth a 1000 words :-)

![image](https://user-images.githubusercontent.com/2370364/67618199-7b086100-f7ec-11e9-9e71-f40481dab3c8.png)

**Comment by bahmutov** [comment]
Do you mind submitting a PR with this fix and also the restore function’s type?

**Comment by iangregsondev** [comment]
Sure, no problems. On it now.
